# Generated by Django 6.0.8 on 2026-09-23 10:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField()),
                ("score", models.DecimalField(decimal_places=5, max_digits=6)),
                ("explanation", models.JSONField(default=dict)),
                ("engine_version", models.CharField(default="hybrid-v1", max_length=32)),
                ("context_hash", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="employees.employee",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.event"
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
                "indexes": [
                    models.Index(
                        fields=["employee", "context_hash"], name="recommendat_employe_4b3d3f_idx"
                    )
                ],
            },
        ),
    ]
