# Generated by Django 6.0.8 on 2026-09-23 10:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("name_en", models.CharField(max_length=255)),
                ("name_ru", models.CharField(blank=True, max_length=255)),
                ("name_kk", models.CharField(blank=True, max_length=255)),
                ("code", models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("name_en", models.CharField(max_length=255)),
                ("name_ru", models.CharField(blank=True, max_length=255)),
                ("name_kk", models.CharField(blank=True, max_length=255)),
                ("code", models.CharField(max_length=64, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[("hard", "Hard skill"), ("soft", "Soft skill")], max_length=8
                    ),
                ),
                ("description_en", models.TextField(blank=True)),
                ("description_ru", models.TextField(blank=True)),
                ("description_kk", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name_en", models.CharField(max_length=255)),
                ("name_ru", models.CharField(blank=True, max_length=255)),
                ("name_kk", models.CharField(blank=True, max_length=255)),
                ("code", models.CharField(max_length=64)),
                ("rank", models.PositiveSmallIntegerField()),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="catalog.role",
                    ),
                ),
            ],
            options={
                "ordering": ["role_id", "rank"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("name_en", models.CharField(max_length=255)),
                ("name_ru", models.CharField(blank=True, max_length=255)),
                ("name_kk", models.CharField(blank=True, max_length=255)),
                ("code", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=64)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("course", "Course"),
                            ("workshop", "Workshop"),
                            ("mentoring", "Mentoring"),
                            ("project", "Project"),
                            ("assessment", "Assessment"),
                        ],
                        default="course",
                        max_length=16,
                    ),
                ),
                ("description_en", models.TextField(blank=True)),
                ("description_ru", models.TextField(blank=True)),
                ("description_kk", models.TextField(blank=True)),
                ("duration_hours", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("is_mandatory", models.BooleanField(default=False)),
                ("repeatable", models.BooleanField(default=False)),
                ("available_from", models.DateField(blank=True, null=True)),
                ("available_until", models.DateField(blank=True, null=True)),
                (
                    "audience_grades",
                    models.ManyToManyField(blank=True, related_name="events", to="catalog.grade"),
                ),
                (
                    "audience_roles",
                    models.ManyToManyField(blank=True, related_name="events", to="catalog.role"),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="GradeRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "required_level",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=3, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="catalog.grade",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_requirements",
                        to="catalog.skill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSkillGain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "gain",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "max_level",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_gains",
                        to="catalog.event",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_gains",
                        to="catalog.skill",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.UniqueConstraint(
                fields=("role", "code"), name="unique_grade_code_per_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.UniqueConstraint(
                fields=("role", "rank"), name="unique_grade_rank_per_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="graderequirement",
            constraint=models.UniqueConstraint(
                fields=("grade", "skill"), name="unique_grade_skill"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventskillgain",
            constraint=models.UniqueConstraint(
                fields=("event", "skill"), name="unique_event_skill_gain"
            ),
        ),
    ]
