# Generated by Django 6.0.8 on 2026-09-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="eventskillgain",
            constraint=models.CheckConstraint(
                condition=models.Q(("gain__gte", 1), ("gain__lte", 5)), name="event_gain_1_5"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventskillgain",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_level__gte", 1), ("max_level__lte", 5)),
                name="event_max_level_1_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="graderequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(("required_level__gte", 0), ("required_level__lte", 5)),
                name="grade_required_level_0_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="graderequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__gte", 1)), name="grade_priority_positive"
            ),
        ),
    ]
