# Generated by Django 6.0.8 on 2026-09-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_eventskillgain_event_gain_1_5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prerequisites',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='upcoming_sessions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('self_paced', 'Self-paced')], default='online', max_length=16),
        ),
    ]
