# Generated by Django 6.0.8 on 2026-09-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_eventskillgain_event_gain_1_5_and_more"),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="employeeskill",
            constraint=models.CheckConstraint(
                condition=models.Q(("level__gte", 0), ("level__lte", 5)),
                name="employee_skill_level_0_5",
            ),
        ),
    ]
