# Generated by Django 6.0.8 on 2026-09-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeskill_employee_skill_level_0_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='career_goal',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_format',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
