# Generated by Django 6.0.8 on 2026-09-23 10:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("completed", "Completed"),
                            ("missed", "Missed"),
                            ("declined", "Declined"),
                        ],
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("completed_on_time", models.BooleanField(blank=True, null=True)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=128, null=True, unique=True),
                ),
                ("source", models.CharField(default="dataset", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="employees.employee",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participations",
                        to="catalog.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("before_level", models.PositiveSmallIntegerField()),
                ("after_level", models.PositiveSmallIntegerField()),
                ("rule_version", models.CharField(default="v1", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_changes",
                        to="activities.activityhistory",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.skill"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="activityhistory",
            index=models.Index(
                fields=["employee", "status"], name="activities__employe_02684f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="skillchangelog",
            constraint=models.UniqueConstraint(
                fields=("activity", "skill"), name="unique_activity_skill_change"
            ),
        ),
    ]
