# Generated by Django 6.0.8 on 2026-09-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityhistory',
            name='assigned_by',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='activityhistory',
            name='completion_pct',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activityhistory',
            name='external_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='activityhistory',
            name='feedback_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityhistory',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityhistory',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('completed', 'Completed'), ('in_progress', 'In progress'), ('dropped', 'Dropped'), ('no_show', 'No show'), ('declined', 'Declined'), ('overdue', 'Overdue')], max_length=16),
        ),
    ]
